name: CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build and Test
        run: ./build.sh
        shell: bash
      - name: Push to my NuGet
        env:
          NUGET_URL: https://www.myget.org/F/mediatr-ci/api/v3/index.json
          NUGET_API_KEY: ${{ secrets.MYGET_TGMEDIATOR_CI_API_KEY }}
        run: ./push.sh
        shell: bash
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/**/*